### PR TITLE
Add it:async snippet

### PR DESCRIPTION
**Pull request by kpman**
Add `async` callback on `it` will be more useful.
So I created a prefix: `ita` to implement it.

Hope you can add this snippet to this project. Thanks!

### CODE REVIEW

**Comment by andys8** [comment]
Cool, looks like a good idea to me. Could you update the readme file, too?

**Comment by kpman** [comment]
Cool, already updated README by force push.

**Comment by andys8** [comment]
Great, thanks. Will merge and publish in a few days (currently away on vacation).

**Comment by kpman** [comment]
Hi @andys8, do you have any update for this PR?

**Comment by andys8** [comment]
Will aggregate it with more issues and publish a new version soon.

**Pull request merged**
